server:
  port: 8090
spring:
  application:
    name: user
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create