server:
  port: 8091
spring:
  application:
    name: updater
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
cron.time: "*/5 * * * * *"
cron.apikey: "58f1d01c-65c6-4182-a8f0-f9891b1a63fe"